# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "shipping-address-status"
client_id = "8f55b9d981a311e2027ab00a54aac8f7"
application_url = "https://expo-teen-maintaining-know.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://expo-teen-maintaining-know.trycloudflare.com/auth/callback",
  "https://expo-teen-maintaining-know.trycloudflare.com/auth/shopify/callback",
  "https://expo-teen-maintaining-know.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "icon-amsterdam-2023.myshopify.com"
